# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MBContries' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

      pod 'PKHUD'

  # Pods for MBContries

  target 'MBContriesTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MBContriesUITests' do
    # Pods for testing
  end

end
